# ch04

## 4.2

In [1]:
import numpy as np

In [2]:
def mean_squared_error(y, t):
    return 0.5 * np.sum((y-t)**2)

In [3]:
# 设“2”为正确解
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
# 例1：“2”的概率最高的情况（0.6）
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
mean_squared_error(np.array(y), np.array(t))

np.float64(0.09750000000000003)

In [4]:
# 例2：“7”的概率最高的情况（0.6）
y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0]
mean_squared_error(np.array(y), np.array(t))

np.float64(0.5975)

In [5]:
def cross_entropy_error(y, t):
    delta = 1e-7
    return -np.sum(t * np.log(y + delta))

In [6]:
t = [0, 0, 1, 0, 0, 0, 0, 0, 0, 0]
y = [0.1, 0.05, 0.6, 0.0, 0.05, 0.1, 0.0, 0.1, 0.0, 0.0]
cross_entropy_error(np.array(y), np.array(t))

np.float64(0.510825457099338)

In [7]:
y = [0.1, 0.05, 0.1, 0.0, 0.05, 0.1, 0.0, 0.6, 0.0, 0.0]
cross_entropy_error(np.array(y), np.array(t))

np.float64(2.3025840929945454)

In [8]:
import sys, os
sys.path.append(os.pardir)
import numpy as np
from dataset.mnist import load_mnist

(x_train, t_train), (x_test, t_test) = \
    load_mnist(normalize=True, one_hot_label=True)

print(x_train.shape) # (60000, 784)
print(t_train.shape) # (60000, 10)

(60000, 784)
(60000, 10)


In [10]:
train_size = x_train.shape[0]
batch_size = 10
batch_mask = np.random.choice(train_size, batch_size)
x_batch = x_train[batch_mask]
t_batch = t_train[batch_mask]

print(x_batch)
print(t_batch)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [11]:
np.random.choice(60000, 10)

array([40200, 12082, 14902, 18442, 29553,  9858, 59865, 14617, 26667,
       39622])

In [14]:
def cross_entropy_error_onehot(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)

    batch_size = y.shape[0]
    return -np.sum(t * np.log(y + 1e-7)) / batch_size

In [15]:
def cross_entropy_error_index(y, t):
    if y.ndim == 1:
        t = t.reshape(1, t.size)
        y = y.reshape(1, y.size)

    batch_size = y.shape[0]
    return -np.sum(np.log(y[np.arange(batch_size), t] + 1e-7)) / batch_size

In [18]:
# 示例数据
np.random.seed(42)
batch_size = 3
num_classes = 5

# 模拟模型输出概率（每行和为 1）
y = np.random.rand(batch_size, num_classes)
y = y / y.sum(axis=1, keepdims=True)

# 真实标签（整数索引）
t_int = np.array([0, 2, 4])

# 将整数标签转换为 one-hot
t_onehot = np.eye(num_classes)[t_int]

# 计算损失
loss_onehot = cross_entropy_error_onehot(y, t_onehot)
loss_index = cross_entropy_error_index(y, t_int)

print("预测概率 y:")
print(y)
print("\n整数标签 t_int:", t_int)
print("one-hot 标签 t_onehot:\n", t_onehot)
print("\n使用 one-hot 标签计算的损失:", loss_onehot)
print("使用整数索引标签计算的损失:", loss_index)
print("两者是否相等？", np.allclose(loss_onehot, loss_index))

预测概率 y:
[[0.13319703 0.33810082 0.26031769 0.21289984 0.05548463]
 [0.06528492 0.02430844 0.36250145 0.25157131 0.29633388]
 [0.00928442 0.43746759 0.37546445 0.09577331 0.08201023]]

整数标签 t_int: [0 2 4]
one-hot 标签 t_onehot:
 [[1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]]

使用 one-hot 标签计算的损失: 1.843853891935881
使用整数索引标签计算的损失: 1.843853891935881
两者是否相等？ True
